project:
  type: website
  output-dir: docs
website:
  title: "Sowdamini Sesha Prasad"
  navbar:
    collapse-below: lg
    right:
      - href: index.qmd
        text: About me
      - href: research.qmd
        text: Research 
      - href: blog.qmd
        text: Blog
      - icon: github
        href: https://github.com/SowdaminiSP

format:
  html:
    theme: [flatly,custom.scss]
    #css: styles.css
    #toc: true

editor: visual

